# Generated by Django 5.2.14 on 2026-05-31 05:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(blank=True, max_length=255, verbose_name="标题"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "对话",
                "verbose_name_plural": "对话",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="QueryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.TextField(verbose_name="问题")),
                (
                    "answer_preview",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="回答预览"
                    ),
                ),
                ("latency_ms", models.FloatField(default=0, verbose_name="耗时(ms)")),
                (
                    "retrieval_count",
                    models.IntegerField(default=0, verbose_name="检索条数"),
                ),
                (
                    "model_used",
                    models.CharField(blank=True, max_length=100, verbose_name="模型"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="时间"),
                ),
            ],
            options={
                "verbose_name": "查询日志",
                "verbose_name_plural": "查询日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=20, verbose_name="角色")),
                ("content", models.TextField(verbose_name="内容")),
                (
                    "sources",
                    models.JSONField(blank=True, default=list, verbose_name="来源"),
                ),
                ("latency_ms", models.FloatField(default=0, verbose_name="耗时(ms)")),
                (
                    "model_used",
                    models.CharField(blank=True, max_length=100, verbose_name="模型"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                        verbose_name="对话",
                    ),
                ),
            ],
            options={
                "verbose_name": "消息",
                "verbose_name_plural": "消息",
                "ordering": ["created_at"],
            },
        ),
    ]
