# Generated by Django 5.2.14 on 2026-05-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="文档名")),
                ("file_path", models.TextField(blank=True, verbose_name="文件路径")),
                ("file_size", models.IntegerField(default=0, verbose_name="文件大小")),
                (
                    "format",
                    models.CharField(blank=True, max_length=20, verbose_name="格式"),
                ),
                ("chunk_count", models.IntegerField(default=0, verbose_name="分块数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "文档",
                "verbose_name_plural": "文档",
                "ordering": ["-created_at"],
            },
        ),
    ]
